export const constants = {
    WEB_VERSION: "0.0.1",
    WEB_BUILD: 1,

    //Ui properties
    JOYSTICK_SIZE: 100,
    JOYSTICK_CATCH_DISTANCE: 50,
    TICK: 500, //ms

    //Configuration
    SPLASH_ANIMATION_FADE_IN_DELAY: 1500,
    SPLASH_ANIMATION_FADE_OUT_DELAY: 1800,

    //Resolution breakpoints
    SMALL_DEVICE_BREAKPOINT: 320,
    TABLET_DEVICE_BREAKPOINT: 480,
    BIG_SCREEN_BREAKPOINT: 769,
    FULL_HD_BREAKPOINT: 1920,
    ULTRA_HD_BREAKPOINT: 3840,
    IPHONE_TOP_SAFE_AREA_HEIGHT: 20,
    IPHONE_X_TOP_SAFE_AREA_HEIGHT: 44,
    IPHONE_X_BOTTOM_SAFE_AREA_HEIGHT: 34
};