export const constants = {
    WEB_VERSION: "0.0.1",
    WEB_BUILD: 1,

    //Configuration
    SPLASH_ANIMATION_FADE_IN_DELAY: 500,
    SPLASH_ANIMATION_DELAY: 1500,
    SPLASH_ANIMATION_FADE_OUT_DELAY: 2000,
    FIRST_LOCATION_PERMISSION_REQUEST: 'FIRST_LOCATION_PERMISSION_REQUEST'
};